language: csharp
mono: none
dotnet: 2.0
script:
  - dotnet build
  - dotnet test eCommerceScrapper.Integration.Tests/eCommerceScrapper.Integration.Tests.csproj
  - dotnet test eCommerceScrapper.Tests/eCommerceScrapper.Tests.csproj