language: csharp
mono: none
dotnet: 2.0
install:
  - nuget restore eCommerceScrapper.sln
  #- nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet build
  - dotnet test